@startuml FORIS Текущее состояние

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' https://github.com/plantuml-stdlib/C4-PlantUML
title "Online sales MNP: регистрация заявки"


Enterprise_Boundary(foris,"FORIS"){
    System( customer_management, "Customer Manageent", ".NET Framework")
    System( order_management, "Order Manageent", ".NET Framework")
    System( ocf, "OCF", ".NET Framework")
    System( sales, "Sales", ".NET Framework")
    System( billing, "Billing", ".NET Framework")
    System( spa, "SPA", ".NET Framework")
    System( ocf, "OCF", ".NET Framework")
    System( sups, "SUPS", ".NET Framework")
    System( umrs, "UMRS Storage", "Oracle")
    System( cm_storage, "CM Storage", "Oracle")
    System( om_storage, "OM Storage", "Oracle")
    System( bill_storage, "Billing Storage", "Oracle")
    System( il, "IL", ".NET Framework")
    System( il_uprs, "IL.UPRSG", ".NET Framework")
    System( mg, "Messaging Gateway", ".Net Framework")
}

Enterprise_Boundary(channel,"Каналы продаж и обслуживания"){
    System_Ext(lk, "ЛК", "")
    System_Ext(siebel, "Siebel", "")
    System_Ext(my_mts, "Мой МТС", "")
    System_Ext(uwindow, "Единое окно", "")
}

Enterprise_Boundary(backoffice,"..."){
    System_Ext(sorm, "СОРМ", "")
    System_Ext(sas, "SAS", "")
    System_Ext(big_data, "Big Data", "")
    System_Ext(mts_business, "МТС Бизнес", "")
}

System_Ext(mscp, "MSCP", "")
System_Ext(hp_ium, "HP IUM", "")
System_Ext(gsm, "HLR, VAS, Network", "")
System_Ext( uprs, "ЕСПП", "")
System_Ext( smbp_ppd, "SMBP PPD", "")
System_Ext( rtm, "RTM", "")
System_Ext( md_proxy, "MD.Proxy", "")
System_Ext( ivr, "IVR", "")
System_Ext( smsc, "SMSC", "")


Rel(lk, il, "HTTP/SOA" )
Rel(siebel, il, "HTTP/SOAP" )
Rel(my_mts, il, "HTTP/SOAP" )
Rel(uwindow, il, "HTTP/SOAP" )
Rel(hp_ium, sups, "FTP" )
Rel(mscp, sups, "HTTP/SOAP" )


Rel(rtm, il, "HTTP/SOA" )

Rel(il, customer_management, "HTTP/SOAP" )
Rel(il, order_management, "HTTP/SOAP" )
Rel(il, billing, "HTTP/SOAP" )
Rel(il, sales , "HTTP/SOAP" )
Rel(il, ocf , "HTTP/SOAP" )

Rel_L(order_management, customer_management , "HTTP/SOAP" )
Rel(sales, customer_management , "HTTP/SOAP" )
'Rel(order_management, spa , "HTTP/SOAP" )
Rel_L(ocf, customer_management , "HTTP/SOAP" )
Rel_L(ocf, order_management , "HTTP/SOAP" )
Rel_L(ocf,mscp , "HTTP/SOAP" )

Rel(order_management,spa , "HTTP/SOAP" )
Rel(order_management,md_proxy, "Rabbit" )
Rel(order_management,mg, "HTTP/SOAP" )
Rel(smbp_ppd,order_management, "HTTP/SOAP" )
Rel(smbp_ppd,spa, "HTTP/SOAP" )
Rel(smbp_ppd,il, "HTTP/SOAP" )
Rel(il,smbp_ppd, "HTTP/SOAP" )

Rel(mg,ivr, "Native" )
Rel(mg,smsc, "Native" )
Rel(md_proxy, rtm, "Kafka" )
Rel(spa,mscp , "HTTP/SOAP" )
Rel(mscp, smbp_ppd , "HTTP/SOAP" )
Rel(mscp, hp_ium, "HTTP/SOAP" )
Rel(gsm, hp_ium, "HTTP/SOAP" )
Rel(spa,gsm, "Vendor protocol" )

Rel(uprs,il_uprs, "HTTP/SOAP" )
Rel(il_uprs, billing, "HTTP/SOAP" )

Rel( customer_management, cm_storage, "ADO.NET")
Rel( sales, om_storage, "ADO.NET")
Rel( order_management, om_storage, "ADO.NET")
Rel( billing, bill_storage, "ADO.NET")
Rel( billing, umrs, "ADO.NET")
Rel( sups, umrs, "ADO.NET")

Rel_L( om_storage, cm_storage, "DB link")
Rel_L( bill_storage, cm_storage, "DB link")
Rel_L( bill_storage, umrs, "DB link")

Rel( bill_storage, sas , "DB Link")
Rel( cm_storage, sas , "DB Link")
Rel( cm_storage, big_data, "DB Link")
Rel( cm_storage, sorm, "DB Link")
Rel( umrs, sorm, "DB Link")
Rel( cm_storage, mts_business, "DB Link")
Rel( mts_business, il, "HTTP/SOAP")

@enduml